--**************************
--Tables
--**************************

--Mitarbeiter table
create table mitarbeiter (
oid bigint generated by default as identity,
mandant varchar(20),
name varchar(255) not null,
mail varchar(50) not null,
primary key (oid));

--Aufgabe table
create table aufgabe (
oid bigint generated by default as identity,
mandant varchar(20),
beschreibung varchar(255) not null,
prioritaet varchar(255) not null,
faelligam date not null,
primary key (oid));






--Aufgabe_Bearbeiter Relation Table
create table aufgabe_bearbeiter (
aufgabe_oid bigint not null, 
bearbeiter_oid bigint not null, 
primary key ( aufgabe_oid, bearbeiter_oid));

alter table aufgabe_bearbeiter 
add constraint FK_aufgabe_bearbeiter_TO_bearbeiter 
foreign key (bearbeiter_oid) 
references mitarbeiter;

alter table aufgabe_bearbeiter 
add constraint FK_aufgabe_bearbeiter_TO_aufgabe 
foreign key (aufgabe_oid) 
references aufgabe;


