package de.gaia.tasks.aufgabenservice.guilib.services;


import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import de.gaia.tasks.aufgabenservice.api.local.Aufgabe_;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Aufgabe_FallbackDataGenerator{
	
	/** Fallback-Daten generierung. Diese Methoden werden durch Barrakuda mit dem gewünschten Verhalten befüllt. */
	
	
	/**
	 * Generiert Fallback-Daten für Methoden, die einen einzelnen Aufgabe_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static Aufgabe_ createAufgabeFallback(){
		return null;
	}
	
	/**
	 * Generiert Fallback-Daten für Methoden, die eine Liste von Aufgabe_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static List<Aufgabe_> createAufgabesFallback(){
		return new ArrayList<>();
	}
	
	/**
	 * Generiert Fallback-Daten für Methoden, die ein Optional von Aufgabe_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static Optional<Aufgabe_> createOptionalAufgabeFallback(){
		return Optional.empty();
	}
	
}
