package de.gaia.tasks.aufgabenservice.guilib.services;


import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import de.gaia.tasks.aufgabenservice.api.local.Mitarbeiter_;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Mitarbeiter_FallbackDataGenerator{
	
	/** Fallback-Daten generierung. Diese Methoden werden durch Barrakuda mit dem gewünschten Verhalten befüllt. */
	
	
	/**
	 * Generiert Fallback-Daten für Methoden, die einen einzelnen Mitarbeiter_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static Mitarbeiter_ createMitarbeiterFallback(){
		return null;
	}
	
	/**
	 * Generiert Fallback-Daten für Methoden, die eine Liste von Mitarbeiter_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static List<Mitarbeiter_> createMitarbeitersFallback(){
		return new ArrayList<>();
	}
	
	/**
	 * Generiert Fallback-Daten für Methoden, die ein Optional von Mitarbeiter_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static Optional<Mitarbeiter_> createOptionalMitarbeiterFallback(){
		return Optional.empty();
	}
	
}
