package de.gaia.tasks.aufgabenservice.api.rest;

import de.gaia.tasks.aufgabenservice.api.local.Aufgabe_;
import org.springframework.hateoas.Link;

import java.util.Collection;
import java.util.List;
import java.util.Optional;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public interface Aufgabe_RestClient {

    /**
     * The name of the Base Endpoint
     */
    public static final String AUFGABES = "aufgabes";

    /**
     * Get all the Aufgabes (with matching tenancy).
     *
     * @return a List of all Aufgabes.
     */
    List<Aufgabe_> findAll();

    /**
     * Get all the Aufgabes (with matching tenancy) on a specific endpoint.
     * <p>
     *     For example: <code>http://localhost:80/entitys/1/attribute</code>
     * </p>
     * @param relation
     * @return
     */
    List<Aufgabe_> findAll(Link relation);
    
    /**
     * Get all Aufgabe matched with string due to fuzzy search.
     * @param filter the string for the query
     * @return
     */
    List<Aufgabe_> findFullTextFuzzy(String filter);

    /**
     * Try to find one Aufgabe (with matching tenancy) by its ID / self relation.
     *
     * @param link The ID / self relation of the Aufgabe_.
     * @return an optional of the Aufgabe_.
     */
    Optional<Aufgabe_> findOne(Link link);

    /**
     * Set all the relations, specified by links, on a specific relation endpoint.
     * <p>
     * Example for an Endpoint: <code>http://localhost:80/entitys/1/attribute</code>
     * </p>
     * <p>
     * This method will always (re-) set the associations. The add or delete
     * functionality is not provided at RestClient level.
     * </p>
     *
     * @param endpoint The endpoint of the relation.
     * @param links    The links that are set to be related.
     */
    void setRelations(Link endpoint, Collection<Link> links);
	/**
	 * Set the relation, specified by @relation, on a specific relation endpoint.
	 * <p>
	 * Example for an Endpoint: <code>http://localhost:80/entitys/1/attribute</code>
	 * </p>
	 * <p>
	 * This method will always (re-) set the association. The add or delete
	 * functionality is not provided at RestClient level.
	 * </p>
	 *
	 * @param endpoint The endpoint of the relation.
	 * @param relation    The link that is set to be related.
	 */
	void setRelation(Link endpoint, Link relation);
    /**
     * Create a new Aufgabe_, the returned Aufgabe_ will have the Links and its ID.
     * @param aufgabe The Aufgabe_ to create, it must not contain any links.
     * @return the created Aufgabe_ (with ID).
     */
    Aufgabe_ create(Aufgabe_ aufgabe);

    /**
     * Update the fields of a Aufgabe_ by the {@link Aufgabe_#getId()}.
     *
     * @param aufgabe The updated Aufgabe_ that will be saved.
     * @return the updated version from the REST Server.
     */
    Aufgabe_ update(Aufgabe_ aufgabe);

    /**
     * Try to delete an ID.
     * @param id The link to the id.
     */
    void delete(Link id);
}
