package de.gaia.tasks.aufgabenservice.api.rest;

import de.gaia.tasks.aufgabenservice.api.domain.Mitarbeiter_DTO;
import de.gaia.tasks.aufgabenservice.api.hateoas.Mitarbeiter_Assembler;
import de.gaia.tasks.aufgabenservice.api.local.Mitarbeiter_;
import org.springframework.hateoas.Link;
import org.springframework.hateoas.MediaTypes;
import org.springframework.hateoas.client.Traverson;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.web.client.RestTemplate;

import java.net.URI;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Mitarbeiter_RestClientImpl implements Mitarbeiter_RestClient {
	
	public static final String FIND_FULL_TEXT_FUZZY = "findFullTextFuzzy";
	
	public static final String SEARCH = "search";
	
	/** Used to follow HATEOAS relations. */
    private final Traverson traverson;
    
    /** The restTemplate used for the HTTP Requests. */
    private final RestTemplate restTemplate;
    
    /** Assembler to switch from Mitarbeiter_DTO Resource to Mitarbeiter_ and vice versa. */
    private final Mitarbeiter_Assembler mitarbeiterAssembler = new Mitarbeiter_Assembler();
	
	/**
	 * Create a new Mitarbeiter_RestClient by RestTemplate of the server.
     * @param restTemplate The restTemplate for the HTTP Requests.
     * @param basePath The base URI of the REST Server.
     */
    public Mitarbeiter_RestClientImpl(RestTemplate restTemplate, final URI basePath) {
        this.restTemplate = restTemplate;
        traverson = new Traverson(basePath, MediaTypes.HAL_JSON);
        traverson.setRestOperations(restTemplate);
    }
	
	@Override
	public List<Mitarbeiter_> findFullTextFuzzy(String filter) {
		return traverson.follow(MITARBEITERS, SEARCH, FIND_FULL_TEXT_FUZZY)
				.withTemplateParameters(Collections.singletonMap("q", filter))
				.toObject(Mitarbeiter_Resource.LIST).getContent()
				.stream()
				.map(mitarbeiterAssembler::toBean)
				.collect(Collectors.toList());
	}
	
	@Override
	public List<Mitarbeiter_> findAll() {  
		return traverson
				.follow(MITARBEITERS)
				.toObject(Mitarbeiter_Resource.LIST).getContent()
				
				.stream()
				.map(mitarbeiterAssembler::toBean)
				.collect(Collectors.toList());
	}
	
	@Override
	public List<Mitarbeiter_> findAll(Link relation) {
		URI uri = URI.create(relation.getHref());
		return restTemplate
		 		.exchange(uri, HttpMethod.GET, null, Mitarbeiter_Resource.LIST)
		 		.getBody()
		 		.getContent()
		 		
		 		.stream()
		 		.map(mitarbeiterAssembler::toBean)
		 		.collect(Collectors.toList());
	}
		
	@Override
	public Optional<Mitarbeiter_> findOne(Link link) {
	     URI uri = URI.create(link.getHref());
		Mitarbeiter_Resource resource = restTemplate
				.exchange(uri, HttpMethod.GET, null, Mitarbeiter_Resource.class)
				.getBody();
				
		return Optional.of(mitarbeiterAssembler.toBean(resource));
	}
	
	@Override
	public void setRelations(Link endpoint, Collection<Link> links) {
		String relations = links.stream().map(Link::getHref).collect(Collectors.joining("\n"));
		HttpHeaders headers = new HttpHeaders();
		headers.setContentType(new MediaType("text", "uri-list"));
		restTemplate.exchange(URI.create(endpoint.getHref()), HttpMethod.PUT, new HttpEntity<>(relations, headers), Void.class);
	}
	
	@Override
    public void setRelation(Link endpoint, Link relation) {
    	Optional<Link> rel = Optional.ofNullable(relation);
		if (rel.isPresent()) {
			HttpHeaders headers = new HttpHeaders();
			headers.setContentType(new MediaType("text", "uri-list"));
			restTemplate.exchange(URI.create(endpoint.getHref()), HttpMethod.PUT, new HttpEntity<>(rel.map(Link::getHref).get(), headers), Void.class);
		} else {
			this.delete(endpoint);
		}
    }

		
	@Override
	public Mitarbeiter_ create(Mitarbeiter_ mitarbeiter) {
		URI uri = URI.create(
		traverson.follow(MITARBEITERS).asLink().getHref());
			Mitarbeiter_DTO mitarbeiterDTO = mitarbeiterAssembler.toResource(mitarbeiter).getContent();
			Mitarbeiter_Resource resource = restTemplate.exchange(uri, HttpMethod.POST, new HttpEntity<>(mitarbeiterDTO), Mitarbeiter_Resource.class).getBody();
			return mitarbeiterAssembler.toBean(resource);
	}
	
	@Override
	public Mitarbeiter_ update(Mitarbeiter_ mitarbeiter) {

        URI uri = URI.create(mitarbeiter.getId().getHref());

        Mitarbeiter_DTO mitarbeiterDTO = mitarbeiterAssembler.toResource(mitarbeiter).getContent();

        Mitarbeiter_Resource resource = restTemplate.exchange(uri, HttpMethod.PUT, new HttpEntity<>(mitarbeiterDTO), Mitarbeiter_Resource.class).getBody();

        return mitarbeiterAssembler.toBean(resource);
    }
		
	@Override
	public void delete(Link id) {
		URI uri = URI.create(id.getHref());
		restTemplate.exchange(uri, HttpMethod.DELETE, null, Void.class);
	}
}
