package de.gaia.tasks.aufgabenservice.api.rest;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */

import de.gaia.tasks.aufgabenservice.api.domain.Mitarbeiter_DTO;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.hateoas.Link;
import org.springframework.hateoas.Resource;
import org.springframework.hateoas.Resources;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpMethod;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Mitarbeiter_Resource extends Resource<Mitarbeiter_DTO> {
	/**
     * This is a simple way to get the Resources "class" for the {@link org.springframework.web.client.RestTemplate#exchange(String, HttpMethod, HttpEntity, ParameterizedTypeReference, Object...)}.
     */
    public static final ParameterizedTypeReference<Resources<Mitarbeiter_Resource>> LIST = new ParameterizedTypeReference<Resources<Mitarbeiter_Resource>>() {
    };

    /**
     * Create a new Resource with a blank Mitarbeiter_DTO.
     */
    public Mitarbeiter_Resource() {
        super(new Mitarbeiter_DTO());
    }

    /**
     * Create a new Resource from  a Mitarbeiter_DTO and multiple Resources.
     * @param content The Mitarbeiter_DTO
     * @param links The links to add to the resource
     */
    public Mitarbeiter_Resource(Mitarbeiter_DTO content, Link... links) {
        super(content, links);
    }

    /**
     * Create a new Resource from  a Mitarbeiter_DTO and multiple Resources.
     * @param content The Mitarbeiter_DTO
     * @param links The links to add to the resource
     */
    public Mitarbeiter_Resource(Mitarbeiter_DTO content, Iterable<Link> links) {
        super(content, links);
    }
}
