package de.gaia.tasks.aufgabenservice.api.hateoas;

import de.gaia.tasks.aufgabenservice.api.domain.Aufgabe_DTO;
import de.gaia.tasks.aufgabenservice.api.local.Aufgabe_;
import de.gaia.tasks.aufgabenservice.api.rest.Aufgabe_Resource;
import org.springframework.hateoas.Resource;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Aufgabe_Assembler {

	/**
	 * Transform the Resource (from the REST Server) to the local object representation.
	 *
	 * @param resource the REST DTO Resource
	 * @return the local Object Representation
	 */
	public Aufgabe_ toBean(Resource<Aufgabe_DTO> resource) {

		Aufgabe_DTO aufgabeDTO = resource.getContent();
		Aufgabe_ bean = new Aufgabe_();		bean.setBeschreibung(aufgabeDTO.getBeschreibung());
		bean.setPrioritaet(aufgabeDTO.getPrioritaet());
		bean.setFaelligAm(aufgabeDTO.getFaelligAm());
		bean.add(resource.getLinks());
		return bean;
	}
	
	/**
	 * Transform the local object representation to the DTO resource.
	 *
	 * @param bean the local object representation
	 * @return the REST DTO Resource
	 */
	public Aufgabe_Resource toResource(Aufgabe_ bean) {
		Aufgabe_DTO aufgabeDTO = new Aufgabe_DTO();
		aufgabeDTO.setBeschreibung(bean.getBeschreibung());
		aufgabeDTO.setPrioritaet(bean.getPrioritaet());
		aufgabeDTO.setFaelligAm(bean.getFaelligAm());
		aufgabeDTO.setBearbeiter(bean.getBearbeiter());
		return new Aufgabe_Resource(aufgabeDTO, bean.getLinks());
	}
}
