package de.gaia.tasks.aufgabenservice.api.hateoas;

import de.gaia.tasks.aufgabenservice.api.domain.Mitarbeiter_DTO;
import de.gaia.tasks.aufgabenservice.api.local.Mitarbeiter_;
import de.gaia.tasks.aufgabenservice.api.rest.Mitarbeiter_Resource;
import org.springframework.hateoas.Resource;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Mitarbeiter_Assembler {

	/**
	 * Transform the Resource (from the REST Server) to the local object representation.
	 *
	 * @param resource the REST DTO Resource
	 * @return the local Object Representation
	 */
	public Mitarbeiter_ toBean(Resource<Mitarbeiter_DTO> resource) {

		Mitarbeiter_DTO mitarbeiterDTO = resource.getContent();
		Mitarbeiter_ bean = new Mitarbeiter_();		bean.setName(mitarbeiterDTO.getName());
		bean.setMail(mitarbeiterDTO.getMail());
		bean.add(resource.getLinks());
		return bean;
	}
	
	/**
	 * Transform the local object representation to the DTO resource.
	 *
	 * @param bean the local object representation
	 * @return the REST DTO Resource
	 */
	public Mitarbeiter_Resource toResource(Mitarbeiter_ bean) {
		Mitarbeiter_DTO mitarbeiterDTO = new Mitarbeiter_DTO();
		mitarbeiterDTO.setName(bean.getName());
		mitarbeiterDTO.setMail(bean.getMail());
		return new Mitarbeiter_Resource(mitarbeiterDTO, bean.getLinks());
	}
}
