package de.gaia.tasks.aufgabenservice.api.domain;

import de.muenchen.vaadin.demo.apilib.domain.BaseEntity;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Aufgabe_DTO extends BaseEntity {
	
	private String beschreibung;
	
	private Prioritaet_ prioritaet;
	
	private java.util.Date faelligAm;
	
	private java.util.Collection<String> bearbeiter;
	
	// Getters and Setters
	public String getBeschreibung(){
		return beschreibung;
	}
	public void setBeschreibung(String beschreibung){
		this.beschreibung = beschreibung;
	}
	
	public Prioritaet_ getPrioritaet(){
		return prioritaet;
	}
	public void setPrioritaet(Prioritaet_ prioritaet){
		this.prioritaet = prioritaet;
	}
	
	public java.util.Date getFaelligAm(){
		return faelligAm;
	}
	public void setFaelligAm(java.util.Date faelligAm){
		this.faelligAm = faelligAm;
	}
	
	public java.util.Collection<String> getBearbeiter(){
		return bearbeiter;
	}
	public void setBearbeiter(java.util.Collection<String> value){
		this.bearbeiter = value;
	}
	
	@Override
	public String toString() {
	   	return String.format("%s = {\"beschreibung\": \"%s\", \"prioritaet\": \"%s\", \"faelligAm\": \"%s\"}", getClass(),
	   		this.beschreibung,
	   		this.prioritaet,
	   		this.faelligAm);
	}
}
