package de.gaia.tasks.aufgabenservice.api.domain;

import de.muenchen.vaadin.demo.apilib.domain.BaseEntity;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Mitarbeiter_DTO extends BaseEntity {
	
	private String name;
	
	private String mail;
	
	// Getters and Setters
	public String getName(){
		return name;
	}
	public void setName(String name){
		this.name = name;
	}
	
	public String getMail(){
		return mail;
	}
	public void setMail(String mail){
		this.mail = mail;
	}
	
	@Override
	public String toString() {
	   	return String.format("%s = {\"name\": \"%s\", \"mail\": \"%s\"}", getClass(),
	   		this.name,
	   		this.mail);
	}
}
